name: AI_clone
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.1.0=gpu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=1.3.0=py38h06a4308_0
  - aiohttp=3.8.3=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anyio=3.5.0=py38h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py38h06a4308_0
  - attrs=22.1.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blessings=1.7=py38h06a4308_1002
  - blinker=1.4=py38h06a4308_0
  - blosc=1.21.3=h6a678d5_0
  - bokeh=3.0.3=py38h06a4308_0
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.12.7=ha878542_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.15.1=py38h5eee18b_3
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - comm=0.1.2=py38h06a4308_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=38.0.4=py38h9ce1e76_0
  - cuda-nvcc=12.0.140=0
  - cudatoolkit=11.3.1=ha36c431_9
  - cudnn=8.2.1=cuda11.3_0
  - cupti=11.3.1=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.33=py38h6a678d5_0
  - cytoolz=0.12.0=py38h5eee18b_0
  - daal4py=2021.6.0=py38h79cecc1_1
  - dal=2021.6.0=hdb19cb5_916
  - dask-core=2022.7.0=py38h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.6=pyhd8ed1ab_1
  - dm-tree=0.1.7=py38h47df419_0
  - entrypoints=0.4=py38h06a4308_0
  - etils=1.0.0=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - fftw=3.3.9=h27cfd23_1
  - flatbuffers=2.0.0=h2531618_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py38h5eee18b_0
  - fsspec=2022.11.0=py38h06a4308_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - googleapis-common-protos=1.57.1=pyhd8ed1ab_0
  - gpustat=0.6.0=pyhd3eb1b0_1
  - grpc-cpp=1.46.1=h33aed49_1
  - grpcio=1.42.0=py38hce63b2e_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=3.7.0=py38h737f45e_0
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py38h06a4308_0
  - imagecodecs=2021.8.26=py38hf0132c2_1
  - imageio=2.19.3=py38h06a4308_0
  - importlib-metadata=4.11.3=py38h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.19.2=py38hb070fc8_0
  - ipython=8.10.0=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.2=py38h06a4308_0
  - joblib=1.1.1=py38h06a4308_0
  - jpeg=9e=h7f8727e_0
  - jsonschema=4.17.3=py38h06a4308_0
  - jupyter_client=7.4.9=py38h06a4308_0
  - jupyter_core=5.2.0=py38h06a4308_0
  - jupyter_server=1.23.4=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jxrlib=1.1=h7b6447c_2
  - keras=2.10.0=py38h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.19.4=h568e23c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcurl=7.87.0=h91b91d3_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm11=11.1.0=h9e868ea_6
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.0=h6a678d5_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzopfli=1.0.3=he6710b0_0
  - llvmlite=0.39.1=py38he621ea3_0
  - locket=1.0.0=py38h06a4308_0
  - lxml=4.9.1=py38h1edc446_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=py38h06a4308_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib=3.6.2=py38h06a4308_0
  - matplotlib-base=3.6.2=py38h945d387_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpi=1.0=mpich
  - mpich=3.3.2=external_0
  - multidict=6.0.2=py38h5eee18b_0
  - munkres=1.1.4=py_0
  - nbclassic=0.5.2=py38h06a4308_0
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.5.4=py38h06a4308_0
  - nbformat=5.7.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py38h06a4308_0
  - networkx=2.8.4=py38h06a4308_0
  - nltk=3.7=pyhd3eb1b0_0
  - notebook=6.5.2=py38h06a4308_0
  - notebook-shim=0.2.2=py38h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numba=0.56.4=py38h417a72b_0
  - numexpr=2.8.4=py38he184ba9_0
  - numpy=1.23.5=py38h14f4228_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - nvidia-ml=7.352.0=pyhd3eb1b0_0
  - oauthlib=3.2.1=py38h06a4308_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1t=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=22.0=py38h06a4308_0
  - pandas=1.5.2=py38h417a72b_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py38h6a678d5_2
  - pip=22.3.1=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=py38h06a4308_0
  - platformdirs=2.5.2=py38h06a4308_0
  - ply=3.11=py38_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - promise=2.3=py38h578d9bd_7
  - prompt-toolkit=3.0.36=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.4.0=py38h06a4308_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.7=py38h6a678d5_1
  - pyqt5-sip=12.11.0=py38h6a678d5_1
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2022.7=py38h06a4308_0
  - pywavelets=1.4.1=py38h5eee18b_0
  - pyyaml=6.0=py38h5eee18b_1
  - pyzmq=23.2.0=py38h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2022.7.9=py38h5eee18b_0
  - requests=2.28.1=py38h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-image=0.19.3=py38h6a678d5_1
  - scikit-learn=1.0.2=py38h51133e4_1
  - scikit-learn-intelex=2021.6.0=py38h06a4308_0
  - scipy=1.10.0=py38h14f4228_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py38h06a4308_0
  - sip=6.6.2=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sniffio=1.2.0=py38h06a4308_1
  - soupsieve=2.3.2.post1=py38h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.7.0=hdb19cb5_0
  - tensorboard=2.10.0=py38h06a4308_0
  - tensorboard-data-server=0.6.1=py38h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py38h06a4308_0
  - tensorflow=2.10.0=gpu_py38h11b98a5_0
  - tensorflow-base=2.10.0=gpu_py38h6559e04_0
  - tensorflow-datasets=4.8.2=pyhd8ed1ab_0
  - tensorflow-estimator=2.10.0=py38h06a4308_0
  - tensorflow-metadata=1.12.0=pyhd8ed1ab_0
  - termcolor=2.1.0=py38h06a4308_0
  - terminado=0.17.1=py38h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py38h06a4308_0
  - tornado=6.2=py38h5eee18b_0
  - tqdm=4.64.1=py38h06a4308_0
  - traitlets=5.7.1=py38h06a4308_0
  - typing-extensions=4.4.0=py38h06a4308_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - urllib3=1.26.14=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38h06a4308_4
  - werkzeug=2.2.2=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - wrapt=1.14.1=py38h5eee18b_0
  - xyzservices=2022.9.0=py38h06a4308_1
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py38h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zipp=3.11.0=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - keras-flops==0.1.2
      - libclang==16.0.6
      - protobuf==3.19.6
      - tensorflow-io-gcs-filesystem==0.33.0
prefix: /jet/home/behrens/.conda/envs/AI_clone
